packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  bufferutil: true
  utf-8-validate: true
  keccak: true
onlyBuiltDependencies:
  - esbuild
  - bufferutil
  - utf-8-validate
  - keccak
